# Generated by Django 4.1.2 on 2022-10-27 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_activity_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 8, 56, 4, 704455, tzinfo=datetime.timezone.utc)),
        ),
    ]
